In [29]:
import numpy as np

In [30]:
# Set up array

In [31]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [32]:
neg = np.where(a < 0, True, False)

In [33]:
neg_values = np.count_nonzero(neg)

In [34]:
print("This array has", neg_values, "negative numbers.")

This array has 4 negative numbers.


In [35]:
pos = np.where(a > 0, True, False)

In [36]:
pos_values = np.count_nonzero(pos)

In [38]:
print("This array has", pos_values, "positive numbers.")

This array has 5 positive numbers.


In [39]:
pos_even = np.where(a % 2, True, False)

In [40]:
pos_even_values = np.count_nonzero(pos_even)

In [41]:
print("This array has", {pos_even_values}, "positive even numbers.")

This array has {4} positive even numbers.


In [42]:
add_3 = np.add(a, 3)

In [43]:
add_3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [44]:
a_mean = np.mean(a)

In [45]:
a_mean

3.0

In [46]:
a_squared = np.square(a)

In [47]:
a_squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [48]:
a_mean = np.mean(a)

In [49]:
a_mean

3.0

In [65]:
new_std = a_squared.std()

In [66]:
new_std

144.0243035046516

In [67]:
a_std = np.std(a)

In [53]:
a_std

8.06225774829855

In [54]:
a_subtract = np.subtract(a, 6)

In [55]:
a_subtract

array([ -2,   4,   6,  17,  -8,  -7,  -6,  -6,  -6, -12,  -3, -13])

In [56]:
def z_score(a, a_mean, a_std):
    return (a - a_mean) / a_std

In [57]:
import sys
print (sys.version)

3.9.6 (default, Aug  5 2022, 15:21:02) 
[Clang 14.0.0 (clang-1400.0.29.102)]


In [58]:
import statistics
print('NormalDist' in dir(statistics))

True


In [59]:
test = statistics.NormalDist(6.0, 8.06) 

In [60]:
test

NormalDist(mu=6.0, sigma=8.06)

In [61]:
## z_score = value - mean/std

In [62]:
z_score = np.divide(np.subtract(a, a_mean), a_std)

In [63]:
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [68]:
# Set up array

In [69]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [70]:
type(b)

numpy.ndarray

In [71]:
# Exercise 1 Make a variable called sum_of_a to hold the sum of all the numbers in above list.

In [72]:
sum_of_b = np.sum(b)

In [73]:
sum_of_b

55

In [74]:
# Exercise 2 Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [75]:
min_of_b = np.min(b)

In [76]:
min_of_b

1

In [77]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [78]:
max_of_b = np.max(b)

In [79]:
max_of_b

10

In [80]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [81]:
mean_of_b = np.mean(b)

In [82]:
mean_of_b

5.5

In [83]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [84]:
product_of_b = np.prod(b)

In [85]:
product_of_b

3628800

In [86]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [87]:
squares_of_b = np.square(b)

In [88]:
squares_of_b

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [89]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only

In [90]:
remainder = np.mod(b, 2)

In [95]:
odds_in_b = b[remainder == 1]

In [96]:
odds_in_b

array([1, 3, 5, 7, 9])

In [97]:
type(b)

numpy.ndarray

In [98]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [99]:
no_remainder = np.mod(b, 2)

In [100]:
evens_in_b = b[no_remainder == 0 ]

In [101]:
evens_in_b

array([ 2,  4,  6,  8, 10])

In [102]:
# Set up array

In [103]:
c = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [104]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#    sum_of_b += sum(row)

In [105]:
sum_of_c = np.sum(c)

In [106]:
sum_of_c

33

In [107]:
type(c)

numpy.ndarray

In [108]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

In [109]:
min_of_c = np.min(c)

In [110]:
min_of_c

3

In [111]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [112]:
max_of_c = np.max(c)

In [113]:
max_of_c 

8

In [114]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1])

In [115]:
mean_of_c = np.mean(c)

In [116]:
mean_of_c

5.5

In [117]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#    for number in row:
#        product_of_b *= number

In [118]:
product_of_c = np.prod(c)

In [119]:
product_of_c

20160

In [120]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#    for number in row:
#        squares_of_b.append(number**2)

In [121]:
square_of_c = np.square(c)

In [122]:
square_of_c

array([[ 9, 16, 25],
       [36, 49, 64]])

In [123]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#    for number in row:
#        if(number % 2 != 0):
#           odds_in_b.append(number)

In [124]:
remainder = np.mod(c, 2)

In [125]:
odds_in_c = c[remainder == 1]

In [126]:
odds_in_c

array([3, 5, 7])

In [127]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#    for number in row:
#        if(number % 2 == 0):
#            evens_in_b.append(number)

In [128]:
no_remainder = np.mod(c, 2)

In [129]:
evens_in_c = c[no_remainder == 0 ]

In [130]:
evens_in_c

array([4, 6, 8])

In [131]:
# Exercise 9 - print out the shape of the array b.

In [132]:
c.shape

(2, 3)

In [133]:
# Exercise 10 - transpose the array b.

In [134]:
transposed_c = c.transpose()

In [135]:
transposed_c

array([[3, 6],
       [4, 7],
       [5, 8]])

In [136]:
# Check shape

In [137]:
transposed_c.shape

(3, 2)

In [138]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [139]:
reshaped_c = np.reshape(c, 6)

In [140]:
reshaped_c

array([3, 4, 5, 6, 7, 8])

In [141]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [142]:
reshape_to_matrix = np.reshape(reshaped_c, (6, 1))

In [143]:
reshape_to_matrix

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [144]:
# Check shape

In [145]:
reshape_to_matrix.shape

(6, 1)

In [146]:
type(reshape_to_matrix)

numpy.ndarray

In [147]:
# Set up array

In [148]:
d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [149]:
type(d)

numpy.ndarray

In [150]:
d.dtype

dtype('int64')

In [151]:
# Exercise 1 - Find the min, max, sum, and product of c.

In [152]:
d.min()

1

In [153]:
d.max()

9

In [154]:
d.sum()

45

In [155]:
d.prod()

362880

In [156]:
d.sum()

45

In [157]:
# Exercise 2 - Determine the standard deviation of c.

In [158]:
d.std()

2.581988897471611

In [159]:
# Exercise 3 - Determine the variance of c.

In [160]:
d.var()

6.666666666666667

In [161]:
# Exercise 4 - Print out the shape of the array c

In [162]:
d.shape

(3, 3)

In [163]:
# Exercise 5 - Transpose c and print out transposed result.

In [164]:
dt = d.transpose()

In [165]:
print(dt)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [166]:
# Exercise 6 - Get the dot product of the array c with c. 

In [167]:
d.dot(d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [168]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [169]:
d_sum_trans = (d * dt)

In [170]:
d_sum_trans

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [171]:
d_sum_trans.sum()

261

In [172]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [173]:
d_sum_trans.prod()

131681894400

In [174]:
# Set up array

In [175]:
e = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [176]:
#Check shape

In [177]:
e.shape

(3, 6)

In [178]:
# Exercise 1 - Find the sine of all the numbers in d

In [179]:
np.sin(e)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [180]:
# Exercise 2 - Find the cosine of all the numbers in d

In [181]:
np.cos(e)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [182]:
# Exercise 3 - Find the tangent of all the numbers in d

In [183]:
np.tan(e)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [210]:
# Exercise 4 - Find all the negative numbers in d

In [211]:
neg_nums = np.where(e < 0, True, False)

In [212]:
neg_values = np.count_nonzero(neg_nums)

In [213]:
neg_view = e[e < 0]

In [217]:
neg_view

array([-90, -30, -45, -45])

In [215]:
# Exercise 5 - Find all the positive numbers in d

In [216]:
print("This array has", neg_values, "negative numbers.")

This array has 4 negative numbers.


In [191]:
pos_nums = np.where(e > 0, True, False)

In [192]:
pos_values = np.count_nonzero(pos_nums)

In [193]:
pos_view = e[e > 0]

In [194]:
pos_view

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [195]:
print("This array has", pos_values, "postive numbers.")

This array has 12 postive numbers.


In [196]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [197]:
unique_nums = np.unique(e)

In [198]:
unique_nums

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [199]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [200]:
unique_values = np.count_nonzero(unique_nums)

In [201]:
unique_values

10

In [202]:
# Exercise 8 - Print out the shape of d.

In [203]:
e.shape

(3, 6)

In [204]:
# Exercise 9 - Transpose and then print out the shape of d.

In [205]:
et = e.transpose()

In [206]:
print(et)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [207]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [208]:
reshape_e = np.reshape(e, (9, 2))

In [209]:
reshape_e 

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])